version: '3.8'
services:
  util-service:
    image: util-service
    build:
      context: ./UtilService
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    depends_on:
      - document-service
  document-service:
    image: doc_service
    build:
      context: ./DocumentService
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - document-service-db

  document-service-db:
    image: postgres:14.7-alpine
    container_name: doc-base
    environment:
      # for demo app. No creds should be here
      POSTGRES_USER: doc_user
      POSTGRES_PASSWORD: doc_pswd_01
    ports:
      - "15432:5432"
    volumes:
      - ./infrastructure/create-db.sql:/docker-entrypoint-initdb.d/create-db.sql
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped
  loki:
    image: grafana/loki:3.4.2
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yml:/etc/loki/local-config.yaml
      - loki-data:/loki
    command: -config.file=/etc/loki/local-config.yaml
    restart: unless-stopped

  promtail:
    image: grafana/promtail:3.4.2
    volumes:
      - ./promtail-config.yml:/etc/promtail/config.yml
      - /var/run/docker.sock:/var/run/docker.sock
    command: -config.file=/etc/promtail/config.yml
    restart: unless-stopped
    depends_on:
      - loki

  grafana:
    image: grafana/grafana:11.3.0
    ports:
      - "3000:3000"
    volumes:
      - ./provisioning:/etc/grafana/provisioning
      - grafana-data:/var/lib/grafana
    environment:
     - GF_SECURITY_ADMIN_PASSWORD=admin
    restart: unless-stopped
    depends_on:
      - loki

volumes:
  db-data:
  loki-data:
  grafana-data: