#demo app config, no service-discovery here
documents:
  base-url: http://document-service:8080
logging:
  level:
    root: INFO
  pattern:
    console: "[%thread] %-5level %logger{36} [%X{TASK}] - [%X{correlationId}] %msg%n"
background-task:
  submit:
    repeat-millis: 20
    batch-size: 100
  approve:
    repeat-millis: 40
    batch-size: 100
