spring:
  application:
    name: DocumentService
  datasource:
    url: jdbc:postgresql://localhost:5432/doc_db
    username: doc_user
    password: doc_pswd_01
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: db/changelog/db.changelog-master.yaml
  properties:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
  server:
    port: 8080
logging:
  level:
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS.Z} [%thread] %-5level %logger{36} - [%X{correlationId}] %msg%n"